### ISSUE TITLE
Bug: when running bbx-cron.sh, sometimes gets [mucuaname] - and should be mucuaname

### ISSUE THREAD

**Issue by fernao** [RedeMocambos/baobaxia#101]
Depending on the version of git annex, mucua name is placed inside '[ ]'; take off then in order to create new mucuas while syncronizing (bbx-cron.sh)

**Comment by 20** [comment]
Whereis informations doesn't show anymore.

**Comment by fernao** [comment]
Git annex sends a text in json format; it's hard to split manually the '[dpadua]' and convert to 'dpadua' on the text because there's a lot of other similar occurrences. A better approach would be rewrite the list of objects with a more accure treatment.
