### ISSUE TITLE
Publish as Gallery should keep filename and maybe translate some pattern to title

### ISSUE THREAD

**Issue by 20** [RedeMocambos/baobaxia#138]
I believe we should keep file name to identify file after publishing. It should also translate filename to title using some pattern like:
Artista-Nome_da_Musica.mp3 [translate to] Artista - Nome da Musica

**Comment by fernao** [comment]
- need to change media/models.py;
- there are several url patterns for music; need to adopt/define a pattern (discuss...)

suggestions: 
- s/[\(\[\]\)\._\w]/-
substitui ( ) [ ] . _ e espaço por -

**Comment by fernao** [comment]
The second part (get metadata from file) still not implemented
