### ISSUE TITLE
Refactor paths

### ISSUE THREAD

**Issue by agger-magenta** [RedeMocambos/baobaxia#161]
Use git-annex move to refactor to this scheme

/data/repository/type
Instead of using date, mucua etc.

to make the data resilient wrt changes.

**Comment by 20** [comment]
I believe we should mantain current structure. and we should update path, with git mv, on data, mucua, or type change.

**Comment by agger-magenta** [comment]
OK. The important thing is to always use the time in UTC 0/have tz-aware
times, so everybody agrees what the date is. Maybe also store the file path
with the media when it's saved to a file, for retrieval - this makes it
less brittle wrt transient bugs, e.g. wrong datetime settings.

2015-06-03 6:22 GMT+02:00 Vince <notifications@github.com>:

> I believe we should mantain current structure. and we should update path,
> with git mv, on data, mucua, or type change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedeMocambos/baobaxia/issues/161#issuecomment-108186505>
> .
>



-- 
Carsten Agger
Magenta ApS
Åbogade 15
8200 Århus N

Tlf  +45 2086 5010
http://www.magenta-aps.dk
carstena@magenta-aps.dk

**Comment by fernao** [comment]
Data -> published_data (read only) -> vinculate path
LastModified -> change at update
Creation data -> i.e.: photo of may 23 1956

Add 'git mv' function

**Comment by agger-magenta** [comment]
I think this is "nice to have" and should be closed. Changing the paths is dangerous because of backwards compatibility and should only be done if we have a superior scheme to replace it.
