### ISSUE TITLE
Bug: search not working well

### ISSUE THREAD

**Issue by fernao** [RedeMocambos/baobaxia#173]
Refactor in order to get:

TERM 1 present at
tag_name OR media_name OR media_fone
AND
TERM 2 present at
tag_name OR media_name OR media_fone
...

**Comment by fernao** [comment]
research some library ? https://bitbucket.org/mchaput/whoosh/wiki/Home

**Comment by agger-magenta** [comment]
maybe with django-haystack.

**Comment by fernao** [comment]
This solution is working and I think is ok for 1.0.
I'll keep this solution for now and then we research a better implementation for after.
