### ISSUE TITLE
Media title always set to no title when publishing new media

### ISSUE THREAD

**Issue by 20** [RedeMocambos/baobaxia#184]
It seems to happen on both single and multiple publishing.

**Comment by fernao** [comment]
Reproduced only at multiple upload; checking...

**Comment by fernao** [comment]
pra mim resolveu; posso fechar?

**Comment by 20** [comment]
Il 23/09/2015 12:18, fernao ha scritto:
> pra mim resolveu; posso fechar?
> 

mbora! :)
