### ISSUE TITLE
acentos em tags

### ISSUE THREAD

**Issue by agger-magenta** [RedeMocambos/baobaxia#200]
Voltou o problema com acentos nas tags.

Se uma tag tem acentos, as mídias parecem perder todas suas tags com o comando update-media-state. Eu acreditava que isso foi solucionado com a nova versão de git annex.

```
git annex metadata baobaxia-na-radio-em-berlim-b7d3e.ogg --json
git-annex: <stdout>: commitBuffer: invalid argument (invalid character)
git-annex: metadata: 1 failed
Malformed JSON found on media: Baobáxia no radio em Berlím
```

**Comment by agger-magenta** [comment]
The command `git annex metadata` gives this error on files with accents or other Unicode characters in tags, and because of this, the media lose all tags when synchronizing.

This is on git annex version 5.20150409, which we installed to solve the previous accent-related bug.

The curious thing is that this used to work, so maybe our code is writing the tags differently.

**Comment by sydro** [comment]
Hi, probably 5.20150409 is too old. That bug was fixed in git annex version 5.20150812. I have install git-annex-standalone version from http://neuro.debian.net/install_pkg.html?p=git-annex-standalone (version 6.20160213) and with "baobáxia" tag it works!

```
git annex metadata test-baobaxia-296aa.jpg --json
{"command":"metadata","file":"test-baobaxia-296aa.jpg","d55c189e-8227-41b0-a946-d53f91753c33-tag":["baobia"],"d55c189e-8227-41b0-a946-d53f91753c33-tag-lastchanged":["2016-02-25@11-12-55"],"lastchanged":["2016-02-25@11-12-55"],"note":"d55c189e-8227-41b0-a946-d53f91753c33-tag=baobia\nd55c189e-8227-41b0-a946-d53f91753c33-tag-lastchanged=2016-02-25@11-12-55\nlastchanged=2016-02-25@11-12-55\n","success":true}
```

**Comment by agger-magenta** [comment]
Awesome, thanks!

Den 25-02-2016 kl. 12:25 skrev sYdRo:
>
> Hi, probably 5.20150409 is too old. That bug was fixed in git annex 
> version 5.20150812. I have install git-annex-standalone version from 
> http://neuro.debian.net/install_pkg.html?p=git-annex-standalone 
> (version 6.20160213) and with "baobáxia" tag it works!
>
> |git annex metadata test-baobaxia-296aa.jpg --json 
> {"command":"metadata","file":"test-baobaxia-296aa.jpg","d55c189e-8227-41b0-a946-d53f91753c33-tag":["baobia"],"d55c189e-8227-41b0-a946-d53f91753c33-tag-lastchanged":["2016-02-25@11-12-55"],"lastchanged":["2016-02-25@11-12-55"],"note":"d55c189e-8227-41b0-a946-d53f91753c33-tag=baobia\nd55c189e-8227-41b0-a946-d53f91753c33-tag-lastchanged=2016-02-25@11-12-55\nlastchanged=2016-02-25@11-12-55\n","success":true} 
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RedeMocambos/baobaxia/issues/200#issuecomment-188739839>.
>

-- 
Carsten Agger
Magenta ApS
Incuba, Åbogade 15
DK-8200 Aarhus N

tel +45 3336 9699
dir +45 5060 1476

http://www.magenta.dk
carstena@magenta.dk

**Comment by sydro** [comment]
if you think that is usefull, i can fix install.sh to install git-annex from neuro.debian.net

**Comment by agger-magenta** [comment]
Yes, that would be good! It would be very useful for the installer to 
secure a version of git-annex with no known bugs.

Den 25-02-2016 kl. 13:19 skrev sYdRo:
>
> if you think that is usefull, i can fix install.sh to install 
> git-annex from neuro.debian.net
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RedeMocambos/baobaxia/issues/200#issuecomment-188758165>.
>

-- 
Carsten Agger
Magenta ApS
Incuba, Åbogade 15
DK-8200 Aarhus N

tel +45 3336 9699
dir +45 5060 1476

http://www.magenta.dk
carstena@magenta.dk

**Comment by agger-magenta** [comment]
I have confirmed that the problem is solved by installing the newest git-annex from neurodebian.
If you're going to fix the installer, we can close this ticket!
