### ISSUE TITLE
Não possível publicar conteúdo

### ISSUE THREAD

**Issue by agger-magenta** [RedeMocambos/baobaxia#211]
Na página "Adicionar conteúdo", o botão "Subir arquivo" parece não responder ao click.

Também o bloco 2 da página (os campos de data, licença etc.) não fica escondido embora deveria segundo a línea 97 no arquivo MediaPublish.js:

```
 $('#media_publish .bloco-2').hide();
```

Parece que tem algum vínculo entre o HTML e JavaScript que não funciona segundo a intenção? Estou usando a versão mais nova do código.

**Comment by agger-magenta** [comment]
Agora passou algo um pouco raro: Tentei investigar o problema fazendo breakpoints no debugger de Firefox. E funcionou! 

Mas se faço de novo sem o debugger, volta a não funcionar. Poderia ser uma questão de timing.

**Comment by agger-magenta** [comment]
Gambiarra: Se introduzo um alert na línea antes do hide, o bloco 2 fica escondido e tudo funciona. Se não, não funciona. Não entendo, mas assim posso trabalhar com o sistema até encontramos a solucão.

**Comment by agger-magenta** [comment]
Este problema parece ser real e parece ser causado pelo commit 3bddee9b4051ec134992841239d6f77b409fc79e. 

Depois de fazer "update-templates" vi o problema na hyndla. Revertendo ao commit ed100e34c06bca91694c4682cbf6777097b7e5ac (é dizer, antes do commit das melhoras de performance) a publicação funciona. Os problemas de publicar conteúdo e de publicar galeria parecem ter a mesma fonte, problemas de timing.

@fernao, vc tem alguma ideia de como se pode solucionar?

**Comment by fernao** [comment]
Oi Agger, vi agora seus commits. Estou fazendo todas as correções na branch improve_performance (https://github.com/RedeMocambos/baobaxia/commits/improve_performance).

Crie uma branch a partir da master e faça um merge com a improve_performance. Tentarei olhar no código em alguns dias.

Fiz várias correções de carregamento assíncrono pois manter todo o carregamento a cargo do RequireJS na arquitetura atual estava deixando o sistema muito lento para carregar, pois a aplicação baixava vários templates que não iria utilizar.

Mantive o carregamento via RequireJS apenas dos arquivos essenciais de sistema e joguei todos os templates para serem carregados de forma assíncrona ao acessar a função. Isso requer que se revisite todas as views, caçando eventos e outros elementos que só podem ser ativados após o template em questão estar plenamente carregado.

Na improve_performance, fiz vários ajustes destes e sugiro que eles sejam testados por mais gente para jogarmos para a master.

**Comment by agger-magenta** [comment]
Oi Fernão, obrigado, vou fazer isso! E muito legal!

**Comment by agger-magenta** [comment]
Agora criei o branch e mergei improve_performance com o master, e a publicação funciona!

Mas a seguna coluna não fica escondida. Isso é um erro ou uma ideia nova?

**Comment by fernao** [comment]
Olhando aqui, acho que isso tem a ver com uma ideia que tinha que era de separar as etapas da publicação e só ativar alguns campos após o preenchimento de outros. Como não está funcionando bem, podemos tirar esse código por hora e implementar esse "passo 1, passo 2, passo 3" futuramente.
